### ISSUE TITLE
[roccatswarm] Upgrade to 1.9396 from 1.9392 is failing

### ISSUE THREAD

**Issue by brogers5** [Cossey/choco#1]
The installer keeps failing with error code -3. Minimized log file is attached for reference.
[chocolatey.log](https://github.com/Cossey/choco/files/7092442/chocolatey.log)

From a quick glance, it looks like this version renamed the installer filename (from `ROCCAT Swarm.exe` to `ROCCAT Swarm_v19396.exe`). `chocolateyInstall.ps1` fails because `Install-ChocolateyZipPackage` is not overwriting the old EXE installer, causing `$installExe` to be assigned to the first EXE found in the temp directory, which happens to be the old version. When I run this EXE manually, the installer GUI is actually prompting me to uninstall instead, likely because this is the same version currently installed.

I'd recommend changing `$installExe` to instead read the filename from the ZIP file directly, to be resilient against future filename changes and ensure we're running the correct installer EXE.

**Comment by brogers5** [comment]
Looked into this a bit further now that my work day's done.

The tail end of `chocolateyInstall.ps1` _should've_ cleared out the temp directory after 1.9392 was installed, but for some reason, it was still present on my machine. I suppose the short-term workaround would be to manually clear this out, then retry the upgrade for `$installExe` to be initialized correctly.

**Comment by Cossey** [comment]
Thanks for raising this issue.

When installing, Chocolately downloads to the temp/roccatswarm folder and then gets the files in the folder filtered by exe file extension and runs the first file returned. It should delete it with the `Remove-Item` command but for some reason did not in your case. I wonder if its a matter of the `Install-ChocolatePackage` still disposing of the file handle when ending execution and moving onto the `Remove-Item` command. The reason it works this way is because for some stupid reason, ROCCAT packages the installer exe inside of a zip file, which makes no sense.

To reduce this from happening in the future, I will like tweak the listing of exe files in the folder so it is sorted by descending date created or modified, that way the item at position 0 will be the most recent one that was downloaded/extracted by Chocolatey.

@brogers5 do you still have both install exes in the folder? Can you please let me know if their created or modified dates differ as expected (older exe with an older date, newer exe with a more recent date?).

**Comment by brogers5** [comment]
They do differ - the created timestamp reflects when the attempted Chocolatey install happened, and the modified timestamp remains the same as originally distributed.

For my purposes, your proposed approach ought to work. However, I imagine it could cause issues in downgrade scenarios.

**Comment by Cossey** [comment]
Thanks @brogers5 for this. You are right that it could cause issues in downgrade scenarios. Plus the way this was working was rather hacky.

I have resolved this now by improving the build script so that when it calculates the hash and file size of the zip it will also get the installer file name. This will make sure the exact installer file is specified in the install powershell script for each package version. The temp roccat folder will now only be removed when uninstalling the package. Due to these changes it does not need to be removed every version. 

These package improvements will only apply to the next version of the Roccat Swarm software and onwards.
